### ISSUE TITLE
Flask API to handle CSV Uploads

### ISSUE THREAD

**Issue by aniruddh622003** [aniruddh622003/major-1#6]
Create a **Flask API endpoint** that takes in a CSV uploaded by a user (returns a error if file is not in CSV/Excel format).
The same should also process the data for NULL values and either Remove them or Fill them. (Currently Only removes it)
This CSv should be stored to local disk using file.save. This is necessary so that to use this file by other APIs.
<img width="162" alt="image" src="https://github.com/aniruddh622003/major-1/assets/32842941/d1276720-1e2c-4a21-b338-193c2c562652">

**Comment by aniruddh622003** [comment]
Git commands to get into this branch
```
git fetch origin
git checkout 6-flask-api-to-handle-csv-uploads
```

**Comment by aniruddh622003** [comment]
@rishimadan14 study the API folder of the application. I have created a basic healthchecker route that works. Find how it works. What are REST APIs and HTTP Requests and Responses

**Comment by rishimadan14** [comment]
CSV upload checked ✔
Overriding of new file ✔
